### ISSUE TITLE
doesn't work anymore

### ISSUE THREAD

**Issue by simonbuehler** [076923/python-image-preview#10]
hi,

with latest vscode i get this trace:

2024-01-15 13:01:10.270 [error] [076923.python-image-preview] provider FAILED
2024-01-15 13:01:10.270 [error] TypeError: Cannot read properties of undefined (reading 'id')
	at y.<anonymous> (/home/pi/.vscode-server/extensions/076923.python-image-preview-0.1.2/dist/extension.js:1:2628)
	at Generator.next (<anonymous>)
	at s (/home/pi/.vscode-server/extensions/076923.python-image-preview-0.1.2/dist/extension.js:1:157)

**Comment by simonbuehler** [comment]
any chance this will be fixed?

.stackFrames[0].id seems to fail
```js
findfVariables(e, n, i, t) {
                    return o(this, void 0, void 0, function* () {
                        const o = (yield e.customRequest("stackTrace", { threadId: n }))
                            .stackFrames[0].id,
                            r = (yield e.customRequest("scopes", { frameId: o })).scopes[0]
                                .variablesReference,
                            s = yield e.customRequest("variables", {
                                variablesReference: r,
                            });
                        if (!0 === t) {
                            const n = s.variables.find((e) => "self" === e.name);
                            var a = (yield e.customRequest("variables", {
                                variablesReference: n.variablesReference,
                            })).variables.find((e) => e.name === i);
                        } else a = s.variables.find((e) => e.name === i);
                        return [a, o];
                    });
                }

```
